[versions]
agp = "8.10.0"
kotlin = "2.0.21"
kotlinxSerializationJson = "1.7.3"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.2"
composeBom = "2025.12.01"
composeMaterialIconsExtended = "1.7.6"
ksp = "2.0.21-1.0.28"
hilt-navigation-compose = "1.2.0"
composeNavigation = "2.8.9"
kotlinxCollectionsImmutable = "0.3.8"
hilt-android = "2.56.1"
coroutine = "1.9.0"
jetbrainsKotlinJvm = "2.0.21"
appcompat = "1.7.1"
material = "1.13.0"
coil = "2.7.0"
media3 = "1.2.1"

[libraries]
# Kotlin
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

# Coroutine
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutine" }

# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

# Media3
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3" }
androidx-media3-common = { group = "androidx.media3", name = "media3-common", version.ref = "media3" }
androidx-media3-session = { group = "androidx.media3", name = "media3-session", version.ref = "media3" }

# Compose
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "composeMaterialIconsExtended" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "composeNavigation" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
compose-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }


# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }


# Plgn
plgn-android = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
plgn-kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
plgn-ksp = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
plgn-hilt-android = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt-android" }
plgn-kotlin-compose-compiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
plgn-kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

# Convention Plugin
delight-android-application = { id = "delight.android.application" }
delight-android-compose = { id = "delight.android.compose" }
delight-android-library = { id = "delight.android.library" }
delight-kotlin-library = { id = "delight.kotlin.library" }
delight-feature-library = { id = "delight.feature.library" }
android-library = { id = "com.android.library", version.ref = "agp" }

plugin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
plugin-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }

[bundles]
compose = [
    "compose-material3",
    "compose-ui-graphics",
    "compose-ui", "compose-ui-tooling-preview",
    "androidx-lifecycle-runtime-ktx", "compose-lifecycle-viewmodel",
    "androidx-activity-compose",
    "compose-navigation", "hilt-navigation-compose",
    "compose-foundation",
    "compose-material-icons-extended",
    "coil-compose"
]

media3 = [
    "androidx-media3-exoplayer",
    "androidx-media3-ui",
    "androidx-media3-common",
    "androidx-media3-session"
]
